name: CI Test Suite for RP Core 

on:
  push:
    branches: 
      - 'main'
      - 'test**'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Create env file
        run: |
          touch .env
          echo DATABASE_URL='${{ vars.DATABASE_URL }}' >> .env
          echo JWT_SECRET='${{ vars.JWT_SECRET }}' >> .env
      - name: Run Jest tests with coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          test-script: yarn jest --ci --json --coverage --testLocationInResults --outputFile=report.json --forceExit
          annotations: failed-tests
